POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doea",
    "number": "123456789"
}

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/66533c8b4464dc9506893985


###

DELETE http://localhost:3001/api/persons/65eb68386d8d4782b2b69d66